In [1]:
import pandas as pd
df=pd.read_csv(r"c:\Users\esair\Downloads\test_data.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Card Type,Point Earned
0,6253,15687492,Anderson,596,Germany,Male,32,3,96709.07,2,0,0,41788.37,0,1,GOLD,709
1,4685,15736963,Herring,623,France,Male,43,1,0.00,2,1,1,146379.30,0,2,SILVER,508
2,1732,15721730,Amechi,601,Spain,Female,44,4,0.00,2,1,0,58561.31,0,1,GOLD,281
3,4743,15762134,Liang,506,Germany,Male,59,8,119152.10,2,1,1,170679.74,0,2,SILVER,979
4,4522,15648898,Chuang,560,Spain,Female,27,7,124995.98,1,1,1,114669.79,0,5,SILVER,457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,6413,15598982,Klein,602,Germany,Female,53,5,98268.84,1,0,1,45038.29,1,5,PLATINUM,813
1996,8286,15572631,Ndubuisi,609,France,Male,25,10,0.00,1,0,1,109895.16,0,2,PLATINUM,652
1997,7854,15746674,Miller,730,France,Female,47,7,0.00,1,1,0,33373.26,1,2,PLATINUM,504
1998,1096,15689081,Wu,692,France,Male,29,4,0.00,1,1,0,76755.99,1,3,PLATINUM,686
1999,6930,15651627,White,628,Germany,Male,39,1,115341.19,1,1,1,107674.30,1,4,SILVER,887

# Data Exploration

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RowNumber           2000 non-null   int64
 1   CustomerId          2000 non-null   int64
 2   Surname             2000 non-null   object
 3   CreditScore         2000 non-null   int64
 4   Geography           2000 non-null   object
 5   Gender              2000 non-null   object
 6   Age                 2000 non-null   int64
 7   Tenure              2000 non-null   int64
 8   Balance             2000 non-null   float64
 9   NumOfProducts       2000 non-null   int64
 10  HasCrCard           2000 non-null   int64
 11  IsActiveMember      2000 non-null   int64
 12  EstimatedSalary     2000 non-null   float64
 13  Complain            2000 non-null   int64
 14  Satisfaction Score  2000 non-null   int64
 15  Card Type           2000 non-null   object
 16  Point Earned        2000 non-null   int64
dtypes: float64(2), int64(11), object(4)
memory usage: 265.8+ KB

In [3]:
#finding categoricall columns and numerical columns
df_categorical=df.select_dtypes(include=['object','string']).columns
df_categorical.to_list()

['Surname', 'Geography', 'Gender', 'Card Type']

In [4]:
df_numerical=df.select_dtypes(include='number').columns
df_numerical.tolist()

['RowNumber',
 'CustomerId',
 'CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Complain',
 'Satisfaction Score',
 'Point Earned']

In [5]:
#top 5 rwos and bottom 5 rows
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Card Type,Point Earned
0,6253,15687492,Anderson,596,Germany,Male,32,3,96709.07,2,0,0,41788.37,0,1,GOLD,709
1,4685,15736963,Herring,623,France,Male,43,1,0.00,2,1,1,146379.30,0,2,SILVER,508
2,1732,15721730,Amechi,601,Spain,Female,44,4,0.00,2,1,0,58561.31,0,1,GOLD,281
3,4743,15762134,Liang,506,Germany,Male,59,8,119152.10,2,1,1,170679.74,0,2,SILVER,979
4,4522,15648898,Chuang,560,Spain,Female,27,7,124995.98,1,1,1,114669.79,0,5,SILVER,457

In [6]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Card Type,Point Earned
1995,6413,15598982,Klein,602,Germany,Female,53,5,98268.84,1,0,1,45038.29,1,5,PLATINUM,813
1996,8286,15572631,Ndubuisi,609,France,Male,25,10,0.00,1,0,1,109895.16,0,2,PLATINUM,652
1997,7854,15746674,Miller,730,France,Female,47,7,0.00,1,1,0,33373.26,1,2,PLATINUM,504
1998,1096,15689081,Wu,692,France,Male,29,4,0.00,1,1,0,76755.99,1,3,PLATINUM,686
1999,6930,15651627,White,628,Germany,Male,39,1,115341.19,1,1,1,107674.30,1,4,SILVER,887

In [7]:
#checking if there are any null values
df.isna().sum()

RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

In [8]:
#statistical data
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Point Earned
count,2000.000000,2.000000e+03,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,4952.472500,1.569204e+07,646.053500,39.018000,5.048500,78020.88786,1.525500,0.713500,0.524500,98726.040350,0.19650,3.025000,605.507500
std,2884.100313,7.229764e+04,97.689463,10.364332,2.933675,62134.21718,0.589511,0.452239,0.499524,57470.903307,0.39745,1.412931,229.826987
min,1.000000,1.556578e+07,350.000000,18.000000,0.000000,0.00000,1.000000,0.000000,0.000000,11.580000,0.00000,1.000000,119.000000
25%,2463.500000,1.562917e+07,578.000000,32.000000,2.000000,0.00000,1.000000,0.000000,0.000000,49712.365000,0.00000,2.000000,408.000000
50%,4950.500000,1.569085e+07,646.500000,38.000000,5.000000,99796.46000,1.000000,1.000000,1.000000,98511.730000,0.00000,3.000000,606.500000
75%,7488.250000,1.575346e+07,712.250000,44.000000,8.000000,127872.15250,2.000000,1.000000,1.000000,147317.217500,0.00000,4.000000,803.250000
max,9999.000000,1.581569e+07,850.000000,92.000000,10.000000,216109.88000,4.000000,1.000000,1.000000,199992.480000,1.00000,5.000000,1000.000000

In [9]:
#checking if there are any duplicated values
df.duplicated().sum()

np.int64(0)

In [10]:
#checking unique values
df.nunique()

RowNumber             2000
CustomerId            2000
Surname               1158
CreditScore            411
Geography                3
Gender                   2
Age                     65
Tenure                  11
Balance               1302
NumOfProducts            4
HasCrCard                2
IsActiveMember           2
EstimatedSalary       2000
Complain                 2
Satisfaction Score       5
Card Type                4
Point Earned           732
dtype: int64

In [11]:
#Which geography has the most customers?
df_customer=df.Geography.value_counts().reset_index(name='Coustomers')
df_customer

  Geography  Coustomers
0    France        1020
1   Germany         498
2     Spain         482

In [12]:
import plotly.express as px
fig=px.bar(data_frame=df_customer,x=df_customer['Geography'],y=df_customer['Coustomers'],title='Customers By Geography',text_auto=True,color_discrete_sequence=['skyblue'])
fig.update_layout(
    width=900,
    height=500,
    title_x=0.5
)
fig.write_image("customers_by_geography.png")
fig.show()

In [13]:
#Which gender raises the most complaints?
df_gender=df.groupby(['Gender'])['Complain'].sum().reset_index(name='Complain')
df_gender

   Gender  Complain
0  Female       220
1    Male       173

In [14]:
fig=px.pie(data_frame=df_gender,names="Complain")
fig.show()

In [15]:
#What is the distribution of card types?
df_card=df['Card Type'].value_counts(normalize=True)*100
df_card

Card Type
SILVER      25.70
GOLD        25.15
DIAMOND     25.15
PLATINUM    24.00
Name: proportion, dtype: float64

In [16]:
#What percentage of customers have a credit card?
df_credit=df.HasCrCard
df_credit
fig=px.pie(data_frame=df_credit,names='HasCrCard')
fig.write_image('ss.png')
fig.show()

In [17]:
#What percentage are active members?
df_active=df['IsActiveMember'].value_counts(normalize=True)*100
df_active

IsActiveMember
1    52.45
0    47.55
Name: proportion, dtype: float64

In [18]:
#What is the distribution of satisfaction scores?
df_satisfaction=df[ 'Satisfaction Score'].value_counts(normalize=True)*100
df_satisfaction

Satisfaction Score
5    21.05
2    20.95
3    20.10
4    19.05
1    18.85
Name: proportion, dtype: float64

In [19]:
#What is the distribution of credit scores?
df_creid_score=df['CreditScore'].value_counts(normalize=True)*100
df_creid_score

CreditScore
850    2.10
646    0.75
678    0.70
584    0.65
682    0.65
       ...
827    0.05
416    0.05
414    0.05
429    0.05
458    0.05
Name: proportion, Length: 411, dtype: float64

In [20]:
#What is the average balance by geography?
df_avg=df.groupby('Geography').agg({'Balance':'mean'})
df_avg

                 Balance
Geography
France      64190.174461
Germany    118457.204659
Spain       65510.601349

In [21]:
#What is the average salary by geography?
df_salary=df.groupby('Geography').agg({'EstimatedSalary':'mean'})
df_salary

           EstimatedSalary
Geography
France        98552.256912
Germany       99076.475783
Spain         98731.729689

In [22]:
df_numerical

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Complain', 'Satisfaction Score', 'Point Earned'],
      dtype='object')

In [23]:
#Which age group has the most customers?
df_age=df.groupby('Age').size().reset_index(name='customers')
df_age

    Age  customers
0    18          4
1    19          5
2    20          7
3    21          9
4    22         15
..  ...        ...
60   82          1
61   84          1
62   85          1
63   88          1
64   92          1

[65 rows x 2 columns]

In [24]:
#Find Age using the available features.
df_1=df.copy()
df_1=df.select_dtypes(include='number')
df_1=df_1.corr()
df_1.corr()['Age']

RowNumber            -0.090212
CustomerId           -0.142823
CreditScore          -0.100883
Age                   1.000000
Tenure               -0.129951
Balance               0.008837
NumOfProducts        -0.117283
HasCrCard            -0.072450
IsActiveMember        0.005904
EstimatedSalary      -0.173258
Complain              0.464150
Satisfaction Score   -0.072001
Point Earned         -0.101438
Name: Age, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error,r2_score
x=df[['Balance','HasCrCard','IsActiveMember','Complain']]
y=df['Age']
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
x_train,x_valid,y_train,y_valid=train_test_split(x_train,y_train,random_state=42,test_size=0.25)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_valid=scaler.transform(x_valid)
x_test=scaler.transform(x_test)
model=LinearRegression()
model.fit(x_train,y_train)
new_data=[[75000,1,1,0]]
new_data_scaled=scaler.transform(new_data)
y_valid_pred=model.predict(new_data_scaled)
print(y_valid_pred)
# print(mean_absolute_error(y_valid,y_valid_pred))
# print(root_mean_squared_error(y_valid,y_valid_pred))
# print(mean_squared_error(y_valid,y_valid_pred))
# print(r2_score(y_valid,y_valid_pred))

[39.20289259]

c:\Users\esair\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
x=df[['Geography','Point Earned','Balance']].copy()
y=df['Card Type']
encoder=OneHotEncoder(sparse_output=False)
geo_encoded=encoder.fit_transform(x[['Geography']])
x = x.drop('Geography', axis=1)
import numpy as np
x = np.hstack((geo_encoded, x.values))
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
model=KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(classification_report(y_test,y_pred))

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [27]:
from sklearn.model_selection import GridSearchCV
params={'n_neighbors':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]}
Grid=GridSearchCV(
    KNeighborsClassifier(),
    params,cv=5,
    scoring='accuracy'    
)
Grid.fit(x_train,y_train)
print(Grid.best_params_)
best_model=Grid.best_estimator_
print(best_model)

{'n_neighbors': 5}
KNeighborsClassifier()

In [43]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=19,max_depth=35)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

     DIAMOND       0.30      0.30      0.30       105
        GOLD       0.27      0.29      0.28        94
    PLATINUM       0.23      0.23      0.23        96
      SILVER       0.26      0.24      0.25       105

    accuracy                           0.27       400
   macro avg       0.26      0.26      0.26       400
weighted avg       0.26      0.27      0.26       400

In [44]:
from sklearn.model_selection import GridSearchCV
params={'n_estimators':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,30],
    'max_depth':[3,5,7,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,42]
        }
Grid=GridSearchCV(
    RandomForestClassifier(),
    params,cv=5,
    scoring='accuracy'    
)
Grid.fit(x_train,y_train)
print(Grid.best_params_)
best_model=Grid.best_estimator_
print(best_model)

KeyboardInterrupt:

In [47]:
y_pred = best_model.predict(x_test)
print(y_pred)
print(classification_report(y_test,y_pred))

['PLATINUM' 'PLATINUM' 'PLATINUM' 'DIAMOND' 'GOLD' 'DIAMOND' 'SILVER'
 'PLATINUM' 'DIAMOND' 'SILVER' 'GOLD' 'PLATINUM' 'GOLD' 'DIAMOND'
 'DIAMOND' 'SILVER' 'SILVER' 'SILVER' 'DIAMOND' 'DIAMOND' 'SILVER' 'GOLD'
 'DIAMOND' 'PLATINUM' 'PLATINUM' 'PLATINUM' 'SILVER' 'GOLD' 'GOLD'
 'PLATINUM' 'DIAMOND' 'DIAMOND' 'SILVER' 'DIAMOND' 'PLATINUM' 'SILVER'
 'PLATINUM' 'GOLD' 'PLATINUM' 'PLATINUM' 'PLATINUM' 'GOLD' 'SILVER'
 'SILVER' 'SILVER' 'GOLD' 'GOLD' 'GOLD' 'GOLD' 'GOLD' 'DIAMOND' 'GOLD'
 'DIAMOND' 'DIAMOND' 'PLATINUM' 'DIAMOND' 'GOLD' 'GOLD' 'DIAMOND' 'SILVER'
 'DIAMOND' 'PLATINUM' 'DIAMOND' 'GOLD' 'PLATINUM' 'DIAMOND' 'PLATINUM'
 'PLATINUM' 'PLATINUM' 'DIAMOND' 'DIAMOND' 'DIAMOND' 'GOLD' 'GOLD' 'GOLD'
 'GOLD' 'PLATINUM' 'DIAMOND' 'GOLD' 'DIAMOND' 'GOLD' 'DIAMOND' 'SILVER'
 'DIAMOND' 'GOLD' 'PLATINUM' 'SILVER' 'SILVER' 'DIAMOND' 'SILVER'
 'PLATINUM' 'PLATINUM' 'DIAMOND' 'DIAMOND' 'PLATINUM' 'SILVER' 'GOLD'
 'DIAMOND' 'SILVER' 'SILVER' 'DIAMOND' 'PLATINUM' 'GOLD' 'PLATINUM'
 'SILVER' 'SILVER' 'PLATINUM' 'PLATINUM' 'SILVER' 'GOLD' 'SILVER'
 'PLATINUM' 'GOLD' 'DIAMOND' 'PLATINUM' 'GOLD' 'PLATINUM' 'GOLD' 'DIAMOND'
 'PLATINUM' 'DIAMOND' 'GOLD' 'DIAMOND' 'DIAMOND' 'DIAMOND' 'DIAMOND'
 'GOLD' 'SILVER' 'SILVER' 'SILVER' 'GOLD' 'DIAMOND' 'GOLD' 'GOLD'
 'PLATINUM' 'SILVER' 'SILVER' 'SILVER' 'PLATINUM' 'PLATINUM' 'DIAMOND'
 'DIAMOND' 'PLATINUM' 'DIAMOND' 'DIAMOND' 'GOLD' 'GOLD' 'SILVER' 'SILVER'
 'SILVER' 'SILVER' 'DIAMOND' 'SILVER' 'SILVER' 'PLATINUM' 'DIAMOND'
 'PLATINUM' 'GOLD' 'GOLD' 'SILVER' 'SILVER' 'PLATINUM' 'PLATINUM'
 'PLATINUM' 'SILVER' 'GOLD' 'PLATINUM' 'GOLD' 'PLATINUM' 'SILVER'
 'PLATINUM' 'GOLD' 'PLATINUM' 'GOLD' 'PLATINUM' 'SILVER' 'DIAMOND'
 'DIAMOND' 'GOLD' 'GOLD' 'GOLD' 'GOLD' 'PLATINUM' 'PLATINUM' 'GOLD' 'GOLD'
 'GOLD' 'DIAMOND' 'SILVER' 'SILVER' 'DIAMOND' 'PLATINUM' 'GOLD' 'GOLD'
 'DIAMOND' 'SILVER' 'PLATINUM' 'SILVER' 'GOLD' 'SILVER' 'GOLD' 'GOLD'
 'DIAMOND' 'GOLD' 'GOLD' 'DIAMOND' 'PLATINUM' 'SILVER' 'PLATINUM' 'GOLD'
 'SILVER' 'SILVER' 'SILVER' 'SILVER' 'DIAMOND' 'GOLD' 'SILVER' 'DIAMOND'
 'SILVER' 'DIAMOND' 'SILVER' 'SILVER' 'SILVER' 'PLATINUM' 'GOLD' 'SILVER'
 'GOLD' 'DIAMOND' 'PLATINUM' 'DIAMOND' 'GOLD' 'SILVER' 'DIAMOND' 'DIAMOND'
 'PLATINUM' 'GOLD' 'GOLD' 'GOLD' 'GOLD' 'SILVER' 'DIAMOND' 'PLATINUM'
 'PLATINUM' 'GOLD' 'GOLD' 'DIAMOND' 'GOLD' 'GOLD' 'SILVER' 'SILVER' 'GOLD'
 'SILVER' 'PLATINUM' 'DIAMOND' 'DIAMOND' 'SILVER' 'GOLD' 'SILVER' 'SILVER'
 'SILVER' 'DIAMOND' 'PLATINUM' 'DIAMOND' 'SILVER' 'SILVER' 'SILVER' 'GOLD'
 'DIAMOND' 'GOLD' 'GOLD' 'DIAMOND' 'DIAMOND' 'SILVER' 'DIAMOND' 'DIAMOND'
 'PLATINUM' 'PLATINUM' 'GOLD' 'SILVER' 'SILVER' 'GOLD' 'DIAMOND' 'GOLD'
 'PLATINUM' 'DIAMOND' 'GOLD' 'SILVER' 'SILVER' 'DIAMOND' 'DIAMOND' 'GOLD'
 'GOLD' 'GOLD' 'SILVER' 'DIAMOND' 'SILVER' 'SILVER' 'PLATINUM' 'DIAMOND'
 'PLATINUM' 'SILVER' 'SILVER' 'PLATINUM' 'SILVER' 'DIAMOND' 'DIAMOND'
 'PLATINUM' 'SILVER' 'DIAMOND' 'PLATINUM' 'PLATINUM' 'PLATINUM' 'PLATINUM'
 'SILVER' 'GOLD' 'DIAMOND' 'DIAMOND' 'PLATINUM' 'DIAMOND' 'SILVER'
 'DIAMOND' 'SILVER' 'DIAMOND' 'PLATINUM' 'PLATINUM' 'DIAMOND' 'PLATINUM'
 'PLATINUM' 'PLATINUM' 'SILVER' 'DIAMOND' 'SILVER' 'PLATINUM' 'SILVER'
 'GOLD' 'SILVER' 'SILVER' 'SILVER' 'SILVER' 'DIAMOND' 'GOLD' 'DIAMOND'
 'PLATINUM' 'PLATINUM' 'DIAMOND' 'GOLD' 'GOLD' 'DIAMOND' 'PLATINUM'
 'DIAMOND' 'PLATINUM' 'PLATINUM' 'GOLD' 'GOLD' 'PLATINUM' 'DIAMOND'
 'SILVER' 'GOLD' 'DIAMOND' 'DIAMOND' 'DIAMOND' 'SILVER' 'SILVER'
 'PLATINUM' 'PLATINUM' 'GOLD' 'GOLD' 'GOLD' 'PLATINUM' 'SILVER' 'DIAMOND'
 'GOLD' 'DIAMOND' 'PLATINUM' 'PLATINUM' 'PLATINUM' 'DIAMOND' 'GOLD'
 'SILVER' 'PLATINUM' 'DIAMOND' 'SILVER' 'DIAMOND' 'SILVER' 'PLATINUM'
 'GOLD' 'DIAMOND' 'DIAMOND' 'DIAMOND' 'SILVER' 'DIAMOND' 'PLATINUM'
 'PLATINUM' 'GOLD' 'GOLD' 'SILVER' 'SILVER' 'PLATINUM' 'DIAMOND' 'GOLD']
              precision    recall  f1-score   support

     DIAMOND       0.30      0.30      0.30       105
        GOLD       0.28      0.30      0.29        94
    PLATINUM       0.23      0.23      0.23        96
      SILVER       0.25      0.24      0.24       105

    accuracy                           0.27       400
   macro avg       0.26      0.27      0.26       400
weighted avg       0.26      0.27      0.26       400